// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function DeleteThumbnail(arg1) {
  return window['go']['main']['App']['DeleteThumbnail'](arg1);
}

export function LoadLibrary() {
  return window['go']['main']['App']['LoadLibrary']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function PickThumbnail() {
  return window['go']['main']['App']['PickThumbnail']();
}

export function RestoreWindow() {
  return window['go']['main']['App']['RestoreWindow']();
}

export function SaveLibrary(arg1) {
  return window['go']['main']['App']['SaveLibrary'](arg1);
}

export function SteamImport(arg1) {
  return window['go']['main']['App']['SteamImport'](arg1);
}

export function ThumbnailHandler() {
  return window['go']['main']['App']['ThumbnailHandler']();
}
