// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {http} from '../models';

export function CopyText(arg1:string):Promise<void>;

export function DeleteThumbnail(arg1:string):Promise<void>;

export function LoadLibrary():Promise<Array<main.Game>>;

export function OpenExternal(arg1:string):Promise<void>;

export function PickThumbnail():Promise<string>;

export function RestoreWindow():Promise<void>;

export function SaveLibrary(arg1:Array<main.Game>):Promise<void>;

export function SteamImport(arg1:string):Promise<main.SteamImportResult>;

export function ThumbnailHandler():Promise<http.Handler>;
